import { Image, Modal, StyleSheet, Text, TouchableOpacity, View } from 'react-native';

const FirstTimeHelpTooltip = ({ onClose }) => {
  return (
    <Modal visible transparent animationType="fade" onRequestClose={onClose}>
      <View style={styles.overlay}>
        <View style={styles.tooltip}>
          <TouchableOpacity style={styles.closeButton} onPress={onClose}>
            <Text style={{ fontSize: 30, color: '#000' }}>×</Text>
          </TouchableOpacity>
          <Image source={require('../../assets/logo192.png')} style={styles.image} />
          <Text style={styles.text}>
            The media button opens a live media view to display images generated by Liva in real time.
          </Text>
        </View>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.15)',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    paddingTop: 50,
    paddingRight: 50,
  },
  tooltip: {
    backgroundColor: '#fff',
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    width: 250,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 11,
    alignItems: 'center',
    position: 'relative',
  },
  closeButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    padding: 5,
  },
  image: {
    width: 100,
    height: 100,
    marginBottom: 10,
  },
  text: {
    fontSize: 14,
    color: '#333',
    textAlign: 'center',
  },
});

export default FirstTimeHelpTooltip;
